package dao;

import connection.ConnectionFactory;
import java.beans.PropertyDescriptor;
import java.lang.reflect.*;
import java.math.BigInteger;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

public class AbstractDAO<T> {
    protected static final Logger LOGGER = Logger.getLogger(AbstractDAO.class.getName());
    private final Class<T> type;

    @SuppressWarnings("unchecked")
    public AbstractDAO() {
        this.type = (Class<T>) ((ParameterizedType) getClass().getGenericSuperclass()).getActualTypeArguments()[0];
    }

    private String createSelectQuery(String field) {
        return "SELECT * FROM " + type.getSimpleName() + " WHERE " + field + " =?";
    }
    /**
     * Retrieves all records from the database table corresponding to the type {@code T}.
     *
     * @return a list of all instances of {@code T} from the database,
     *         or {@code null} if a database error occurs.
     */
    public List<T> findAll() {
        Connection connection = null;
        PreparedStatement statement = null;
        ResultSet resultSet = null;
        String query = "SELECT * FROM " + type.getSimpleName();

        try {
            connection = ConnectionFactory.getConnection();
            statement = connection.prepareStatement(query);
            resultSet = statement.executeQuery();
            return createObjects(resultSet);
        } catch (SQLException e) {
            LOGGER.log(Level.WARNING, type.getName() + "DAO:findAll " + e.getMessage());
        } finally {
            ConnectionFactory.close(resultSet);
            ConnectionFactory.close(statement);
            ConnectionFactory.close(connection);
        }
        return null;
    }

    public T findById(int id) {
        Connection connection = null;
        PreparedStatement statement = null;
        ResultSet resultSet = null;
        String query = createSelectQuery("id");
        try {
            connection = ConnectionFactory.getConnection();
            statement = connection.prepareStatement(query);
            statement.setInt(1, id);
            resultSet = statement.executeQuery();
            return createObjects(resultSet).get(0);
        } catch (SQLException e) {
            LOGGER.log(Level.WARNING, type.getName() + "DAO:findById " + e.getMessage());
        } finally {
            ConnectionFactory.close(resultSet);
            ConnectionFactory.close(statement);
            ConnectionFactory.close(connection);
        }
        return null;
    }

    private List<T> createObjects(ResultSet resultSet) {
        List<T> list = new ArrayList<>();
        Constructor[] ctors = type.getDeclaredConstructors();
        Constructor ctor = null;
        for (Constructor constructor : ctors) {
            ctor = constructor;
            if (ctor.getGenericParameterTypes().length == 0)
                break;
        }
        try {
            while (resultSet.next()) {
                ctor.setAccessible(true);
                T instance = (T) ctor.newInstance();
                for (Field field : type.getDeclaredFields()) {
                    String fieldName = field.getName();
                    Object value = resultSet.getObject(fieldName);

                    if (fieldName.equals("id") && value != null) {
                        if (value instanceof BigInteger) {
                            value = ((BigInteger) value).intValue();
                        } else if (value instanceof Long) {
                            value = ((Long) value).intValue();
                        }
                    }

                    PropertyDescriptor propertyDescriptor = new PropertyDescriptor(fieldName, type);
                    Method method = propertyDescriptor.getWriteMethod();
                    method.invoke(instance, value);
                }
                list.add(instance);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return list;
    }
    /**
     * Inserts a new record into the database for the given object {@code t}.
     * The object's ID field will be set to the value generated by the database, if applicable.
     *
     * @param t the object to insert into the database
     * @return the same object with the generated ID set, or {@code null} if the insert fails
     */
    public T insert(T t) {
        Connection connection = null;
        PreparedStatement statement = null;

        StringBuilder fields = new StringBuilder();
        StringBuilder values = new StringBuilder();
        for (Field field : type.getDeclaredFields()) {
            if (!field.getName().equalsIgnoreCase("id")) {
                fields.append(field.getName()).append(",");
                values.append("?,");
            }
        }
        fields.setLength(fields.length() - 1);
        values.setLength(values.length() - 1);

        String query = "INSERT INTO " + type.getSimpleName() + " (" + fields + ") VALUES (" + values + ")";

        try {
            connection = ConnectionFactory.getConnection();
            statement = connection.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);

            int index = 1;
            for (Field field : type.getDeclaredFields()) {
                if (!field.getName().equalsIgnoreCase("id")) {
                    field.setAccessible(true);
                    statement.setObject(index++, field.get(t));
                }
            }

            statement.executeUpdate();
            ResultSet generatedKeys = statement.getGeneratedKeys();
            if (generatedKeys.next()) {
                Field idField = type.getDeclaredField("id");
                idField.setAccessible(true);
                Object idValue = generatedKeys.getObject(1);

                if (idValue instanceof BigInteger) {
                    idValue = ((BigInteger) idValue).intValue();
                } else if (idValue instanceof Long) {
                    idValue = ((Long) idValue).intValue();
                }

                idField.set(t, idValue);
            }
            return t;
        } catch (Exception e) {
            LOGGER.log(Level.WARNING, type.getName() + "DAO:insert " + e.getMessage());
        } finally {
            ConnectionFactory.close(statement);
            ConnectionFactory.close(connection);
        }
        return null;
    }
    /**
     * Updates the existing database record corresponding to the given object {@code t}.
     * The object must have a valid ID set for the update to succeed.
     *
     * @param t the object containing updated field values
     * @return the updated object, or {@code null} if the update fails
     */
    public T update(T t) {
        Connection connection = null;
        PreparedStatement statement = null;

        StringBuilder query = new StringBuilder();
        query.append("UPDATE ").append(type.getSimpleName()).append(" SET ");

        List<Field> fields = new ArrayList<>();
        Field idField = null;

        for (Field field : type.getDeclaredFields()) {
            if (field.getName().equalsIgnoreCase("id")) {
                idField = field;
            } else {
                query.append(field.getName()).append("=?, ");
                fields.add(field);
            }
        }

        query.setLength(query.length() - 2);
        query.append(" WHERE id=?");

        try {
            connection = ConnectionFactory.getConnection();
            statement = connection.prepareStatement(query.toString());

            int index = 1;
            for (Field field : fields) {
                field.setAccessible(true);
                statement.setObject(index++, field.get(t));
            }

            if (idField != null) {
                idField.setAccessible(true);
                statement.setObject(index, idField.get(t));
            }

            statement.executeUpdate();
            return t;
        } catch (Exception e) {
            LOGGER.log(Level.WARNING, type.getName() + "DAO:update " + e.getMessage());
        } finally {
            ConnectionFactory.close(statement);
            ConnectionFactory.close(connection);
        }
        return null;
    }
    /**
     * Deletes the record with the specified ID from the database.
     *
     * @param id the ID of the record to delete
     * @return {@code true} if the record was successfully deleted; {@code false} otherwise
     */
    public boolean delete(int id) {
        Connection connection = null;
        PreparedStatement statement = null;

        String query = "DELETE FROM " + type.getSimpleName() + " WHERE id = ?";

        try {
            connection = ConnectionFactory.getConnection();
            statement = connection.prepareStatement(query);
            statement.setInt(1, id);
            return statement.executeUpdate() > 0;
        } catch (SQLException e) {
            LOGGER.log(Level.WARNING, type.getName() + "DAO:delete " + e.getMessage());
        } finally {
            ConnectionFactory.close(statement);
            ConnectionFactory.close(connection);
        }
        return false;
    }
}

